export interface CategoryConfig {
  id: string;
  name: string;
  hindiName: string;
  department: string;
  defaultSlaDays: number;
  iconName: string;
  subcategories: { name: string; hindiName: string; defaultSeverity: "Critical" | "High" | "Medium" | "Low" }[];
  keywords: string[];
}

export const INITIAL_CATEGORIES: CategoryConfig[] = [
  {
    id: "water",
    name: "Water Supply",
    hindiName: "जल आपूर्ति / पेयजल",
    department: "Drinking Water & Sanitation Department (DWSD)",
    defaultSlaDays: 3,
    iconName: "Droplet",
    keywords: ["water", "paani", "nal", "tap", "pipeline", "handpump", "chaapkal", "supply", "leakage", "dirty water", "drinking water", "jal", "boring"],
    subcategories: [
      { name: "Drinking Water Contamination", hindiName: "दूषित पेयजल", defaultSeverity: "Critical" },
      { name: "Handpump / Chapakal Breakdown", hindiName: "हैंडपंप / चापाकल खराबी", defaultSeverity: "Medium" },
      { name: "Pipeline Leakage / Burst", hindiName: "पाइपलाइन लीकेज / टूटना", defaultSeverity: "High" },
      { name: "No Supply / Low Pressure", hindiName: "जल आपूर्ति ठप / कम दबाव", defaultSeverity: "High" },
    ],
  },
  {
    id: "electricity",
    name: "Electricity",
    hindiName: "विद्युत / बिजली",
    department: "Jharkhand Bijli Vitran Nigam Ltd (JBVNL)",
    defaultSlaDays: 2,
    iconName: "Zap",
    keywords: ["bijli", "electricity", "power", "transformer", "wire", "voltage", "blackout", "street light", "meter", "load shedding", "current"],
    subcategories: [
      { name: "Transformer Burnout / Failure", hindiName: "ट्रांसफार्मर जलना / खराबी", defaultSeverity: "Critical" },
      { name: "Street Light Failure", hindiName: "स्ट्रीट लाइट खराबी", defaultSeverity: "Medium" },
      { name: "Prolonged Power Outage", hindiName: "लंबे समय से बिजली गुल", defaultSeverity: "High" },
      { name: "Dangling Live Wire Hazard", hindiName: "लटकता हुआ खुला तार", defaultSeverity: "Critical" },
      { name: "Billing / Meter Dispute", hindiName: "मीटर / बिलिंग समस्या", defaultSeverity: "Low" },
    ],
  },
  {
    id: "roads",
    name: "Roads & Bridges",
    hindiName: "सड़क एवं पुल",
    department: "Road Construction Department (RCD) / Rural Development",
    defaultSlaDays: 7,
    iconName: "Navigation",
    keywords: ["road", "sadak", "pothole", "gaddha", "bridge", "pul", "tar", "footpath", "highway", "drain cover", "broken road", "accident zone"],
    subcategories: [
      { name: "Severe Potholes & Road Damage", hindiName: "गंभीर गड्ढे एवं सड़क क्षति", defaultSeverity: "High" },
      { name: "Bridge / Culvert Collapse Risk", hindiName: "पुलिया / पुल ढहने का खतरा", defaultSeverity: "Critical" },
      { name: "Unpaved Rural Connectivity", hindiName: "कच्ची सड़क / संपर्क मार्ग अभाव", defaultSeverity: "Medium" },
      { name: "Missing Manhole Cover", hindiName: "खुला मैनहोल / नाले का ढक्कन", defaultSeverity: "Critical" },
    ],
  },
  {
    id: "sanitation",
    name: "Sanitation & Waste",
    hindiName: "स्वच्छता एवं कचरा प्रबंधन",
    department: "Urban Local Bodies / Swachh Bharat Mission (Gramin)",
    defaultSlaDays: 2,
    iconName: "Trash2",
    keywords: ["kachra", "garbage", "sanitation", "safai", "drain", "naali", "sewer", "dustbin", "dead animal", "overflowing", "dump"],
    subcategories: [
      { name: "Garbage Pile Overflow", hindiName: "कचरे का ढेर / दुर्गंध", defaultSeverity: "High" },
      { name: "Open Drain Overflow & Clogging", hindiName: "नाली जाम / गंदा पानी सड़क पर", defaultSeverity: "High" },
      { name: "Dead Animal Removal", hindiName: "मृत पशु हटाना", defaultSeverity: "Critical" },
      { name: "Community Toilet Inoperable", hindiName: "सामुदायिक शौचालय खराबी", defaultSeverity: "Medium" },
    ],
  },
  {
    id: "scholarship",
    name: "Scholarship & Student Aid",
    hindiName: "छात्रवृत्ति एवं प्रोत्साहन",
    department: "Welfare Department / Higher & Technical Education",
    defaultSlaDays: 5,
    iconName: "GraduationCap",
    keywords: ["scholarship", "ekalyan", "e-kalyan", "welfare", "st/sc/obc", "post matric", "pre matric", "nsp", "fellowship", "chhatravriti", "fee", "stipend"],
    subcategories: [
      { name: "e-Kalyan Disbursement Delay", hindiName: "ई-कल्याण छात्रवृत्ति लंबित", defaultSeverity: "High" },
      { name: "Document Verification Stuck", hindiName: "संस्थान सत्यापन अटका हुआ", defaultSeverity: "Medium" },
      { name: "Aadhaar / Bank DBT Link Issue", hindiName: "डीबीटी / बैंक खाता त्रुटि", defaultSeverity: "Medium" },
      { name: "Portal Rejection Discrepancy", hindiName: "अकारण पोर्टल अस्वीकृति", defaultSeverity: "Medium" },
    ],
  },
  {
    id: "pension",
    name: "Social Security & Pension",
    hindiName: "पेंशन एवं सामाजिक सुरक्षा",
    department: "Department of Social Welfare & Social Security",
    defaultSlaDays: 5,
    iconName: "HeartHandshake",
    keywords: ["pension", "vridha", "widow", "vidhwa", "divyang", "old age", "disability", "payment", "bank", "dbt", "kishori", "senior"],
    subcategories: [
      { name: "Old Age Pension Payment Stopped", hindiName: "वृद्धावस्था पेंशन रुकी हुई", defaultSeverity: "High" },
      { name: "Widow Pension Approval Pending", hindiName: "विधवा पेंशन स्वीकृति लंबित", defaultSeverity: "Medium" },
      { name: "Divyang / Disability Aid Delay", hindiName: "दिव्यांग पेंशन / उपकरण सहायता", defaultSeverity: "High" },
      { name: "Annual Life Certificate / Biometric Failure", hindiName: "जीवन प्रमाण पत्र सत्यापन त्रुटि", defaultSeverity: "Medium" },
    ],
  },
  {
    id: "pds",
    name: "PDS & Food Security",
    hindiName: "राशन एवं खाद्य सुरक्षा",
    department: "Food, Public Distribution & Consumer Affairs",
    defaultSlaDays: 3,
    iconName: "ShoppingBag",
    keywords: ["ration", "anaj", "dealer", "pds", "chawal", "gehu", "ration card", "dealer", "black marketing", "pos machine", "grain", "food"],
    subcategories: [
      { name: "Ration Dealer Refusal / Less Quantity", hindiName: "डीलर द्वारा कम अनाज या मनाही", defaultSeverity: "High" },
      { name: "Ration Card Addition / Deletion Issue", hindiName: "राशन कार्ड में नाम जोड़ना/त्रुटि", defaultSeverity: "Medium" },
      { name: "PoS Biometric Device Failure", hindiName: "पीओएस मशीन बायोमेट्रिक विफलता", defaultSeverity: "High" },
      { name: "Substandard Quality Grains", hindiName: "खराब गुणवत्ता का खाद्यान्न", defaultSeverity: "High" },
    ],
  },
  {
    id: "health",
    name: "Health & Medical Services",
    hindiName: "स्वास्थ्य एवं चिकित्सा सेवाएँ",
    department: "Health, Medical Education & Family Welfare",
    defaultSlaDays: 1,
    iconName: "Activity",
    keywords: ["hospital", "doctor", "medicine", "dawa", "ambulance", "chc", "phc", "sadar", "ayushman", "treatment", "delivery", "swasthya", "clinic"],
    subcategories: [
      { name: "Doctor / Staff Absenteeism in PHC/CHC", hindiName: "प्राथमिक स्वास्थ्य केंद्र में डॉक्टर अनुपस्थित", defaultSeverity: "Critical" },
      { name: "Essential Medicine Stock-Out", hindiName: "आवश्यक दवाइयों की अनुपलब्धता", defaultSeverity: "High" },
      { name: "Ayushman Card Denial at Hospital", hindiName: "अस्पताल में आयुष्मान कार्ड अस्वीकार", defaultSeverity: "Critical" },
      { name: "Emergency 108 Ambulance Failure", hindiName: "108 एम्बुलेंस अनुपलब्धता", defaultSeverity: "Critical" },
    ],
  },
  {
    id: "education",
    name: "School & Higher Education",
    hindiName: "विद्यालय एवं उच्च शिक्षा",
    department: "Department of School Education & Literacy",
    defaultSlaDays: 6,
    iconName: "BookOpen",
    keywords: ["school", "teacher", "madhyamik", "mid day meal", "mdm", "books", "uniform", "college", "classroom", "toilet", "vidyalaya", "shiksha"],
    subcategories: [
      { name: "Mid-Day Meal (MDM) Quality / Non-supply", hindiName: "मध्याह्न भोजन गुणवत्ता / रुकावट", defaultSeverity: "Critical" },
      { name: "Teacher Shortage / Chronic Absenteeism", hindiName: "शिक्षकों की कमी / अनुपस्थिति", defaultSeverity: "High" },
      { name: "School Girls Toilet / Clean Water Lack", hindiName: "बालिका शौचालय / पेयजल अभाव", defaultSeverity: "High" },
      { name: "Free Textbooks & Uniform Delay", hindiName: "मुफ्त पाठ्यपुस्तक एवं पोशाक विलंब", defaultSeverity: "Medium" },
    ],
  },
  {
    id: "agriculture",
    name: "Agriculture & Farmers",
    hindiName: "कृषि एवं किसान कल्याण",
    department: "Agriculture, Animal Husbandry & Co-operative Department",
    defaultSlaDays: 5,
    iconName: "Sprout",
    keywords: ["kisan", "farmer", "fasal", "crop", "beej", "seed", "fertilizer", "khad", "pmkisan", "fasal bima", "drought", "sukha", "irrigation"],
    subcategories: [
      { name: "PM-KISAN Instalment Delay", hindiName: "पीएम-किसान सम्मान निधि किस्त लंबित", defaultSeverity: "Medium" },
      { name: "Fertilizer / Seed Black Marketing", hindiName: "उर्वरक / बीज की कालाबाजारी", defaultSeverity: "High" },
      { name: "Crop Damage Relief Claim Pending", hindiName: "फसल क्षति राहत मुआवजा लंबित", defaultSeverity: "High" },
      { name: "Canal / Irrigation Lift Breakdown", hindiName: "नहर / लिफ्ट सिंचाई पंप खराबी", defaultSeverity: "High" },
    ],
  },
  {
    id: "schemes",
    name: "Government Schemes",
    hindiName: "सरकारी योजनाएँ",
    department: "Planning & Development Department",
    defaultSlaDays: 5,
    iconName: "Layers",
    keywords: ["yojana", "scheme", "subsidy", "awas", "housing", "patt", "land", "grant", "subsidy", "labharthi", "benefit"],
    subcategories: [
      { name: "PM Awas Yojana Instalment Delay", hindiName: "पीएम आवास योजना किस्त नहीं मिली", defaultSeverity: "High" },
      { name: "Scheme Beneficiary List Exclusion", hindiName: "पात्र होने पर भी सूची से वंचित", defaultSeverity: "Medium" },
      { name: "Subsidy Transfer Pending", hindiName: "सब्सिडी राशि बैंक में लंबित", defaultSeverity: "Medium" },
    ],
  },
  {
    id: "employment",
    name: "Employment & MGNREGA",
    hindiName: "रोजगार एवं मनरेगा",
    department: "Rural Development / Labour, Employment & Training",
    defaultSlaDays: 4,
    iconName: "Briefcase",
    keywords: ["mgnrega", "manrega", "job card", "majdoori", "wage", "labour", "employment", "rozgar", "work demand"],
    subcategories: [
      { name: "MGNREGA Wage Payment Delay", hindiName: "मनरेगा मजदूरी भुगतान में देरी", defaultSeverity: "High" },
      { name: "Job Card Issuance Refusal", hindiName: "जॉब कार्ड जारी करने से मनाही", defaultSeverity: "Medium" },
      { name: "Work Allocation Denial", hindiName: "काम की मांग पर रोजगार न मिलना", defaultSeverity: "High" },
    ],
  },
  {
    id: "public_safety",
    name: "Public Safety & Law",
    hindiName: "जन सुरक्षा एवं नागरिक व्यवस्था",
    department: "Home, Prison & Disaster Management (Police)",
    defaultSlaDays: 1,
    iconName: "ShieldAlert",
    keywords: ["police", "patrol", "theft", "harassment", "eve teasing", "unsafe", "dark street", "gang", "cctv", "noise", "safety", "suraksha"],
    subcategories: [
      { name: "Unsafe Dark Stretches / Harassment Prone Area", hindiName: "अंधेरे सुनसान मार्ग / छेड़खानी का जोखिम", defaultSeverity: "Critical" },
      { name: "Delayed Police Assistance / Station Indifference", hindiName: "थाने में सुनवाई न होना / विलंब", defaultSeverity: "High" },
      { name: "Illegal Encroachment Causing Hazard", hindiName: "अवैध अतिक्रमण जिससे खतरा हो", defaultSeverity: "Medium" },
    ],
  },
  {
    id: "transport",
    name: "Public Transport & Traffic",
    hindiName: "परिवहन एवं यातायात",
    department: "Transport Department",
    defaultSlaDays: 4,
    iconName: "Bus",
    keywords: ["bus", "auto", "traffic", "signal", "transport", "overcharging", "bus stand", "route", "permit"],
    subcategories: [
      { name: "Non-Availability of Rural Bus Service", hindiName: "ग्रामीण बस सेवा की अनुपलब्धता", defaultSeverity: "Medium" },
      { name: "Traffic Signal Breakdown", hindiName: "ट्रैफिक सिग्नल खराबी", defaultSeverity: "High" },
      { name: "Rampant Fare Overcharging", hindiName: "बस/ऑटो किराया मनमाना वसूली", defaultSeverity: "Low" },
    ],
  },
  {
    id: "anganwadi",
    name: "Anganwadi & Child Welfare",
    hindiName: "आंगनवाड़ी एवं बाल विकास",
    department: "Women, Child Development & Social Security",
    defaultSlaDays: 3,
    iconName: "Baby",
    keywords: ["anganwadi", "poshan", "nutrition", "sewika", "bal vikas", "pregnant", "dhatri", "toddler", "vaccine", "supplement"],
    subcategories: [
      { name: "Anganwadi Center Locked / Sewika Absent", hindiName: "आंगनवाड़ी केंद्र बंद / सेविका अनुपस्थित", defaultSeverity: "High" },
      { name: "Poshan Take-Home Ration Not Distributed", hindiName: "पोषण आहार वितरण न होना", defaultSeverity: "High" },
      { name: "Immunization / Health Checkup Disrupted", hindiName: "टीकाकरण / वजन मापन बाधित", defaultSeverity: "Critical" },
    ],
  },
  {
    id: "infrastructure",
    name: "Public Infrastructure & Civic Assets",
    hindiName: "सार्वजनिक बुनियादी ढांचा",
    department: "Urban Development & Housing Department",
    defaultSlaDays: 5,
    iconName: "Building2",
    keywords: ["community hall", "park", "playground", "crematorium", "boundary wall", "civic building", "panchayat bhavan", "bhavan", "infrastructure"],
    subcategories: [
      { name: "Panchayat Bhavan Dilapidated Condition", hindiName: "पंचायत भवन जर्जर हालत", defaultSeverity: "Medium" },
      { name: "Public Park / Playground Neglect", hindiName: "सार्वजनिक पार्क / खेल मैदान बदहाली", defaultSeverity: "Low" },
      { name: "Community Hall Encroachment", hindiName: "सामुदायिक भवन पर अवैध कब्जा", defaultSeverity: "High" },
    ],
  },
  {
    id: "environment",
    name: "Environment & Pollution",
    hindiName: "पर्यावरण एवं प्रदूषण",
    department: "Jharkhand State Pollution Control Board (JSPCB) / Forest",
    defaultSlaDays: 4,
    iconName: "Trees",
    keywords: ["pollution", "pradushan", "smoke", "factory", "river pollution", "tree cutting", "mining dust", "smell", "chemical"],
    subcategories: [
      { name: "Industrial Air / Coal Dust Pollution", hindiName: "औद्योगिक धुआं / कोयला धूल प्रदूषण", defaultSeverity: "High" },
      { name: "River / Stream Chemical Waste Discharge", hindiName: "नदी / जलस्रोत में जहरीला कचरा बहाना", defaultSeverity: "Critical" },
      { name: "Illegal Tree Felling / Green Cover Loss", hindiName: "अवैध वृक्ष कटाई", defaultSeverity: "High" },
    ],
  },
  {
    id: "other",
    name: "Other Civic Issues",
    hindiName: "अन्य नागरिक समस्याएँ",
    department: "District Grievance Cell / Deputy Commissioner Office",
    defaultSlaDays: 5,
    iconName: "HelpCircle",
    keywords: ["other", "any", "general", "misc", "samanya", "problem", "complaint"],
    subcategories: [
      { name: "General Administrative Delay", hindiName: "प्रशासनिक कार्य में अकारण विलंब", defaultSeverity: "Medium" },
      { name: "Land Record / Mutation Dispute", hindiName: "दाखिल खारिज / जमीन रसीद समस्या", defaultSeverity: "High" },
      { name: "Civic Public Nuisance", hindiName: "सार्वजनिक उपद्रव / बाधा", defaultSeverity: "Low" },
    ],
  },
];
