import { GovernmentScheme } from "../types";

export const GOVERNMENT_SCHEMES: GovernmentScheme[] = [
  {
    id: "sch-ekalyan",
    name: "e-Kalyan Post-Matric Scholarship Scheme",
    department: "Scheduled Tribe, Scheduled Caste, Minority and Backward Class Welfare Department",
    targetAudience: ["Students", "Tribal Communities"],
    shortDescription: "Financial assistance for post-matriculation higher studies to eligible SC, ST, and OBC domicile students of Jharkhand.",
    eligibility: "Jharkhand domicile. SC/ST family annual income < ₹2.5 Lakhs; BC/OBC family annual income < ₹1.5 Lakhs. Enrolled in recognized post-secondary diploma/degree course.",
    benefits: "Tuition fee reimbursement up to 100% + maintenance allowance up to ₹10,000/year credited directly via DBT.",
    requiredDocuments: ["Aadhaar Card", "Jharkhand Residential Certificate", "Caste Certificate", "Income Certificate (Current FY)", "College Bonafide Certificate", "Previous Exam Marksheet", "Bank Passbook linked with Aadhaar"],
    applicationProcess: "Apply online at ekalyan.cgg.gov.in. Upload scanned certificates. Institute verification is mandatory within 15 days.",
    deadline: "30 October 2026",
    link: "https://ekalyan.cgg.gov.in",
    isScholarship: true,
    category: "Scholarship",
  },
  {
    id: "sch-nsp-pre",
    name: "National Scholarship Portal (NSP) Central Sector Schemes",
    department: "Ministry of Education & Social Justice, Govt of India",
    targetAudience: ["Students"],
    shortDescription: "Centrally sponsored scholarship for college and university students securing top 20th percentile in Class 12 board examinations.",
    eligibility: "Score above 80th percentile in Class 12. Pursuing regular courses in medical, engineering, or arts/commerce/science. Family income < ₹4.5 Lakhs/year.",
    benefits: "₹12,000 per annum at Graduation level for first 3 years, and ₹20,000 per annum at Post-Graduation level.",
    requiredDocuments: ["Class 12 Marksheet", "Aadhaar Card", "Income Certificate", "Bonafide Student Certificate", "Bank Passbook"],
    applicationProcess: "Register at scholarships.gov.in using Aadhaar/Aadhaar Enrollment ID and institute code.",
    deadline: "15 November 2026",
    link: "https://scholarships.gov.in",
    isScholarship: true,
    category: "Scholarship",
  },
  {
    id: "sch-pm-yasasvi",
    name: "PM-YASASVI Post-Matric Scholarship for OBC & EBC",
    department: "Ministry of Social Justice and Empowerment",
    targetAudience: ["Students"],
    shortDescription: "Scholarship for Other Backward Classes (OBC), Economically Backward Classes (EBC), and Nomadic Tribes pursuing higher education.",
    eligibility: "Belong to OBC/EBC/DNT categories. Family income not exceeding ₹2.5 Lakhs. Studying in Class 11-12 or college degree.",
    benefits: "Covers tuition fees, hostel allowance, and academic materials stipend up to ₹1,25,000/year for top institutions.",
    requiredDocuments: ["OBC/EBC Certificate", "Income Certificate", "Marksheet", "Aadhaar", "Fee Receipt"],
    applicationProcess: "Apply through the National Scholarship Portal under Department of Social Justice tab.",
    deadline: "30 September 2026",
    link: "https://yet.nta.ac.in",
    isScholarship: true,
    category: "Scholarship",
  },
  {
    id: "sch-aicte-pragati",
    name: "AICTE Pragati Scholarship for Female Technical Students",
    department: "All India Council for Technical Education (AICTE)",
    targetAudience: ["Students", "Women"],
    shortDescription: "Empowering girl students taking admission in first year of AICTE approved Diploma or Degree technical programs.",
    eligibility: "Female students admitted to 1st year of Degree/Diploma level course or 2nd year via lateral entry. Family income < ₹8 Lakhs.",
    benefits: "₹50,000 per annum for each year of study towards college fees, computer purchase, books, software, equipment.",
    requiredDocuments: ["Admission letter from AICTE institute", "Tuition fee receipt", "Income affidavit", "Aadhaar card", "Class 10 & 12 Marksheets"],
    applicationProcess: "Apply on National Scholarship Portal after institute physical verification.",
    deadline: "31 October 2026",
    link: "https://www.aicte-india.org/schemes/students-development-schemes/Pragati",
    isScholarship: true,
    category: "Scholarship",
  },
  {
    id: "sch-pmkisan",
    name: "Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)",
    department: "Department of Agriculture & Farmers Welfare",
    targetAudience: ["Farmers"],
    shortDescription: "Direct income support of ₹6,000 per year in three equal instalments to all landholding farmer families across Jharkhand.",
    eligibility: "Small and marginal farmers with cultivable landholding in their name. e-KYC and land seeding mandatory.",
    benefits: "₹6,000 per year transferred directly to bank account in 3 instalments of ₹2,000 every four months.",
    requiredDocuments: ["Land Revenue Record (Khatiyan / Jamabandi)", "Aadhaar Card", "Bank Account linked with NPCI/DBT", "Mobile number linked to Aadhaar"],
    applicationProcess: "Self-register on pmkisan.gov.in or visit local Pragya Kendra (CSC) for biometric e-KYC verification.",
    deadline: "Ongoing Enrollment",
    link: "https://pmkisan.gov.in",
    category: "Agriculture",
  },
  {
    id: "sch-jrfry",
    name: "Jharkhand Rajya Fasal Rahat Yojana (JRFRY)",
    department: "Department of Agriculture, Animal Husbandry & Co-operative, Jharkhand",
    targetAudience: ["Farmers"],
    shortDescription: "Crop damage relief compensation for rain-fed farmers facing drought or irregular monsoon loss without insurance premium.",
    eligibility: "Farmers of Jharkhand having land ownership or recognized sharecroppers (Bataidar) cultivating kharif crops.",
    benefits: "Compensation of ₹3,000/acre for 30-50% crop loss, and ₹4,000/acre for >50% crop loss up to maximum 5 acres.",
    requiredDocuments: ["Land Revenue Receipt (Lagancop)", "Vanshavali (Genealogy)", "Self-Declaration (Swaghoshna Patra)", "Aadhaar Card", "Bank Passbook"],
    applicationProcess: "Register at jrfry.jharkhand.gov.in before sowing assessment cut-off date.",
    deadline: "15 September 2026",
    link: "https://jrfry.jharkhand.gov.in",
    category: "Agriculture",
  },
  {
    id: "sch-pension-vridha",
    name: "Mukhyamantri Sarvajan Vridha Pension Yojana",
    department: "Department of Women, Child Development and Social Security",
    targetAudience: ["Senior Citizens"],
    shortDescription: "Universal social security pension scheme providing monthly subsistence to all senior citizens aged 50+ (ST/SC/Women) & 60+ (Others).",
    eligibility: "Age 50+ for ST, SC and all women in Jharkhand; age 60+ for general males. Applicant must not be an income tax payee or govt retiree.",
    benefits: "Monthly pension of ₹1,000 deposited straight into beneficiary's savings bank account every month.",
    requiredDocuments: ["Age Proof (Aadhaar / Voter ID / Matriculation certificate)", "Residential Certificate of Jharkhand", "Bank Account Details", "Income/Exclusion Self-Declaration"],
    applicationProcess: "Submit physical application to Block Development Officer (BDO) or apply through Panchayat Sarkar Aapke Dwar camps.",
    deadline: "Open All Year",
    category: "Pension",
  },
  {
    id: "sch-pension-vidhwa",
    name: "Mukhyamantri Rajya Nirashrit Mahila Samman Pension",
    department: "Department of Women, Child Development and Social Security",
    targetAudience: ["Women"],
    shortDescription: "Financial assistance for widowed, abandoned, deserted, or destitute women in Jharkhand to ensure dignity and independence.",
    eligibility: "Female resident of Jharkhand aged 18 years or above who is widowed, divorced, or deserted by husband without regular maintenance.",
    benefits: "Monthly cash assistance of ₹1,000 directly deposited in bank account.",
    requiredDocuments: ["Death certificate of husband (if widowed) / Village Pradhan certification (if abandoned)", "Aadhaar Card", "Bank Passbook", "Residential Proof"],
    applicationProcess: "Apply via Block Office social welfare counter or nearest Pragya Kendra.",
    deadline: "Open All Year",
    category: "Pension",
  },
  {
    id: "sch-ayushman",
    name: "Ayushman Bharat — Mukhyamantri Jan Arogya Yojana",
    department: "Health, Medical Education and Family Welfare Department",
    targetAudience: ["Women", "Senior Citizens", "Farmers", "Tribal Communities"],
    shortDescription: "Cashless health cover up to ₹5 Lakhs per family per year for secondary and tertiary inpatient medical treatments across empanelled hospitals.",
    eligibility: "All NFSA ration card holders and SECC census-listed families in Jharkhand.",
    benefits: "Cashless hospital admission, surgeries, medicines, diagnostics up to ₹5 Lakhs annually at government and private empanelled hospitals.",
    requiredDocuments: ["Ration Card (Pink / Green / Yellow)", "Aadhaar Card of all family members"],
    applicationProcess: "Visit any Sadar Hospital, CHC, or empanelled private hospital Ayushman Mitra desk to generate the golden card.",
    deadline: "Continuous Coverage",
    link: "https://setu.pmjay.gov.in",
    category: "Health",
  },
  {
    id: "sch-pmayg",
    name: "Pradhan Mantri Awas Yojana — Gramin (PMAY-G) & Abua Awas",
    department: "Rural Development Department, Govt of Jharkhand",
    targetAudience: ["Housing", "Tribal Communities", "Farmers"],
    shortDescription: "Financial grant for construction of pucca house with clean kitchen, electricity connection, and piped water supply.",
    eligibility: "Homeless families or households living in kutcha or dilapidated houses in rural areas as per Awas-Plus survey list.",
    benefits: "Cash assistance of ₹2,00,000 in 4 instalments + 95 person-days of MGNREGA wages + ₹12,000 for toilet construction.",
    requiredDocuments: ["Aadhaar Card", "Job Card (MGNREGA)", "Bank Account Details", "Geo-tagged photo of existing kutcha house"],
    applicationProcess: "Gram Sabha validates beneficiary eligibility; registration done by Block Gram Panchayat Secretary.",
    deadline: "Annual Survey Cycle",
    category: "Housing",
  },
  {
    id: "sch-nfsa-ration",
    name: "Jharkhand State Food Security Scheme (Green Ration Card)",
    department: "Department of Food, Public Distribution and Consumer Affairs",
    targetAudience: ["Tribal Communities", "Women", "Farmers"],
    shortDescription: "Subsidized foodgrains for vulnerable families excluded from the Central NFSA list.",
    eligibility: "Poor and marginalized households residing in Jharkhand without existing Central Priority Household (PHH) or Antyodaya cards.",
    benefits: "5 kg rice per person per month at nominal rate of ₹1/kg.",
    requiredDocuments: ["Aadhaar cards of all family members", "Proof of address", "Self-declaration of family income"],
    applicationProcess: "Apply online at aahar.jharkhand.gov.in under 'Apply for New Ration Card' or via Circle Office.",
    deadline: "Open All Year",
    link: "https://aahar.jharkhand.gov.in",
    category: "PDS / Ration",
  },
  {
    id: "sch-birsa-harit",
    name: "Birsa Harit Gram Yojana (Horticulture Orchards)",
    department: "Rural Development Department / MGNREGA",
    targetAudience: ["Farmers", "Tribal Communities"],
    shortDescription: "Promoting fruit orchard plantations (Mango, Guava, Lemon) on fallow private rural land with wage support for 3 years.",
    eligibility: "Farmers with 0.5 to 1 acre of unutilized upland (Tand land). Priority to SC/ST and women-headed households.",
    benefits: "Free 100+ fruit saplings, pit digging and watering wages via MGNREGA, fencing materials, and ₹50,000+ estimated annual income after maturity.",
    requiredDocuments: ["Land Possession Certificate (LPC) / Khatiyan", "MGNREGA Job Card", "Aadhaar Card", "Bank Account"],
    applicationProcess: "Apply at the local Gram Panchayat meeting or Rozgar Sevak.",
    deadline: "30 June 2026 (Plantation Season)",
    category: "Agriculture",
  },
  {
    id: "sch-mukhya-kanya",
    name: "Mukhyamantri Savitribai Phule Kishori Samriddhi Yojana",
    department: "Department of Women, Child Development and Social Security",
    targetAudience: ["Students", "Women"],
    shortDescription: "Financial assistance to adolescent girls from Class 8 to 12 and on attaining 18-19 years to prevent child marriage and promote education.",
    eligibility: "Girl students studying in government/aided schools in Jharkhand. Up to two daughters per family.",
    benefits: "Total incentive of ₹40,000 in stages (Class 8: ₹2,500; Class 9: ₹2,500; Class 10: ₹5,000; Class 11: ₹5,000; Class 12: ₹5,000; Age 18-19: ₹20,000).",
    requiredDocuments: ["School Bonafide / Transfer Certificate", "Aadhaar Card", "Single-holder Bank Account Passbook", "Parental Declaration"],
    applicationProcess: "Submit application form in respective school/Anganwadi center.",
    deadline: "30 September 2026",
    category: "Women & Child",
  },
  {
    id: "sch-skill-jharkhand",
    name: "Hunar Jharkhand — Skill Training & Placement Voucher",
    department: "Jharkhand Skill Development Mission Society (JSDMS)",
    targetAudience: ["Students", "Employment"],
    shortDescription: "Free residential vocational skill training programs in IT, Healthcare, Automotive, Solar, and Electronics with guaranteed job placement.",
    eligibility: "Youth aged 18-35 years who have passed minimum 8th, 10th, or 12th standard, domicile of Jharkhand.",
    benefits: "100% free certified training, course materials, lodging, boarding, uniform, and placement assistance.",
    requiredDocuments: ["Educational Certificates", "Aadhaar Card", "Residential Certificate", "Passport size photographs"],
    applicationProcess: "Register at skilljharkhand.gov.in or visit Mega Skill Center in Ranchi, Jamshedpur, Bokaro, or Dhanbad.",
    deadline: "Batch intake every quarter",
    link: "https://skilljharkhand.gov.in",
    category: "Skill Development",
  },
  {
    id: "sch-pension-divyang",
    name: "Swami Vivekananda Nishakt Swavalamban Protsahan",
    department: "Social Welfare Department, Govt of Jharkhand",
    targetAudience: ["Senior Citizens", "Women"],
    shortDescription: "Monthly financial support for persons with disabilities (Divyangjan) to support living expenses and rehabilitation.",
    eligibility: "Resident of Jharkhand having 40% or more certified permanent disability issued by competent Medical Board.",
    benefits: "₹1,000 per month direct benefit transfer to bank account.",
    requiredDocuments: ["Disability Certificate / UDID Card", "Aadhaar Card", "Jharkhand Domicile Certificate", "Bank Account Passbook"],
    applicationProcess: "Apply at District Social Welfare Office or online via Jharsewa portal.",
    deadline: "Open All Year",
    category: "Pension",
  },
  {
    id: "sch-guruji-credit",
    name: "Guruji Student Credit Card Scheme",
    department: "Higher and Technical Education Department, Jharkhand",
    targetAudience: ["Students"],
    shortDescription: "Collateral-free concessional higher education loans up to ₹15 Lakhs for students pursuing Engineering, Medical, Law, and Management.",
    eligibility: "Domicile of Jharkhand who passed 10th and 12th from Jharkhand institutions. Admitted into NIRF top-ranked universities/colleges.",
    benefits: "Education loan up to ₹15 Lakhs at simple interest rate of just 4% per annum. No collateral or third-party guarantee required.",
    requiredDocuments: ["College Admission Offer Letter", "Fee Structure from Institute", "Aadhaar Card", "10th/12th Marksheets", "Parent/Student KYC"],
    applicationProcess: "Apply on GSCC portal (gscc.jharkhand.gov.in) with student registration ID.",
    deadline: "Open for Academic Session 2026",
    link: "https://gscc.jharkhand.gov.in",
    isScholarship: true,
    category: "Scholarship",
  },
];
